# 选择存储方式
# 1: Config (通常使用, 本地存储. 无需填写其他内容)
# 2: Redis (网络数据库, 可用于多服统一数据, 需要搭建或购买, 也需要配置 redis-settings)
# 3: MySQL (暂不支持)
# 默认: 1
database-type: 1

# 当选择存储方式为数据库时需要添加以下 4 项 (host, port, user, password)
database-server-settings:
  # 数据库服务器地址 localhost 指当前主机
  host: "localhost"
  # 数据库端口号, Redis 默认端口 6379. MySQL 默认端口 3306
  port: 0
  # 数据库账号. Redis 留空, SQL 之类需填写
  user: ""
  # 数据库密码, 无密码留空.
  password: ""

# 当使用 Config 作为数据库时, 保存数据间隔时间. 设置为 0 则有数据修改立即保存
# 默认: 2400 (2分钟)
database-save-tick: 2400

# 货币 1 名称
# 默认: Coin
money-unit-1: "Coin"

# 是否开启货币 2
# 如果设置为 false, 任何关于货币2的功能将禁止使用.
# 默认: true (是)
enable-unit-2: true

# 货币 2 名称 (只有货币1才能存入银行)
# 默认: Point
money-unit-2: "Point"

# 银行利率
# 默认: 0.0003
bank-interest-value: "0.0003"

# 银行利息发放间隔. (真实时间) (单位秒) (修改系统时间会影响利息发放)
# 默认: 86400 (24小时)
bank-interest-time: "86400"

# 是否补发服务器离线时未发放的利息
# 默认: true (是)
bank-interest-real: true

# 玩家第一次进服的初始货币1数量
# 默认: 1000
initial-money-1: "1000"

# 玩家第一次进服的初始货币2数量
# 默认: 0
initial-money-2: "0"

# 玩家第一次进服的初始银行储蓄
# 默认: 0
initial-bank-money: "0"

# 支付货币1时, 玩家最低剩余值
# 默认: 1000
pay-1-limit: "1000"

# 支付货币2时, 玩家最低剩余值
# 默认: 1000
pay-2-limit: "1000"